### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/mdn-minimalist#9]
We currently have some "standard" libraries as part of our `stylelint` tooling that essentially define our CSS/SCSS coding standards:

file: https://github.com/schalkneethling/mdn-minimalist/blob/efd5b03c0b5f10ac79d55f6c8cf36c7175f5afa2/.stylelintrc.json
```
"stylelint-config-standard",
"stylelint-config-recommended-scss",
"stylelint-config-sass-guidelines",
"stylelint-a11y/recommended",
"stylelint-prettier/recommended"
```

That is great, useful and important. The thing I do not like is that **we** do not necessarily know what is inside those black boxes, and that is not good. It also means people writing code will have to kinda write and wait for the tooling to tell them that they have strayed from the path :)

With that in mind, I am thinking we should take the time to understand these "standards" we are opting into, document the most important parts that can be a little surprising to people*, and ensure we actually want to opt into all of the rules/standards they define. For example, `stylelint-config-standard` defaults to 1 level of nesting, which we have agreed is too strict and so we add this to our `stylelint.json`

```
"rules": {
  "max-nesting-depth": 3
}
```

My thinking then is for each of us to grab a package and dig in. Does that sound like a plan/something you would be interested in @mindy?

## Tasks

Review and document the following packages

- [x] ~~stylelint-config-standard~~ dropped in favor of `stylelint-config-recommended`
- [x] ~~stylelint-config-recommended-scss~~
- [x] stylelint-config-sass-guidelines
- [x] stylelint-a11y/recommended
- [x] stylelint-prettier/recommended // not sure that this one will require much if anything, but adding it just to be consistent

*Here I am thinking about stuff like ordering in SCSS files for example, and in general with regards to CSS properties. For example, I really like this pattern:

```
.class {
  @extend .extend;
  @include mixin();
  property/values...
}
```

The above might also not be immediately intuitive to everyone. When it comes to property order it might be even more unclear unless documented clearly, even for us in the beginning.

**Comment by mindy** [comment]
This sounds like a good plan! I can start with `stylelint-config-recommended-scss` if you haven't yet.

I imagine there will be duplicate or overridden rules, so I was envisioning one part of it as a table (like the "Rules" shown [here](https://github.com/YozhikM/stylelint-a11y)), with all the Stylelint rules listed, and what packages, if at all, specify a value. What do you think?

**Comment by schalkneethling** [comment]
> This sounds like a good plan! I can start with `stylelint-config-recommended-scss` if you haven't yet.

Great! I will grab `stylelint-config-standard` then.

> I imagine there will be duplicate or overridden rules, so I was envisioning one part of it as a table (like the "Rules" shown here), with all the Stylelint rules listed, and what packages, if at all, specify a value. What do you think?

Sounds good to me. Once we have consensus on this, I reckon we can officially start to document all of this on the `mdn-fiori` repo using something like 11ty(https://www.11ty.dev/ - mainly because I am looking for a reason to play with it :)) as a means of generating pages and publishing it on gh-pages

**Comment by schalkneethling** [comment]
@mindy Had a look over `stylelint-config-standard`. It is an extension to `stylelint-config-recommended` and mainly adds stylistic rules. Seeing that we are using Prettier, there is very little it adds to justify maintaining updates to the package.

My proposal is to drop `stylelint-config-standard` in favor of `stylelint-config-recommended` but, add the following custom rules to our config:

```
"max-nesting-depth": 2,
declaration-no-important: true, /* https://stylelint.io/user-guide/rules/declaration-no-important */
font-weight-notation: "named-where-possible", /* https://stylelint.io/user-guide/rules/font-weight-notation */
color-hex-length: "short", /* https://stylelint.io/user-guide/rules/color-hex-length */
selector-pseudo-element-colon-notation: "double" /* https://stylelint.io/user-guide/rules/selector-pseudo-element-colon-notation */
```

Let me know your thoughts. Thanks!

**Comment by mindy** [comment]
@schalkneethling I'm in full support of these rules and dropping `stylint-config-standard`. I agree that it doesn't make sense to have it if Prettier takes care of the stylistic rules.

**Comment by schalkneethling** [comment]
> @schalkneethling I'm in full support of these rules and dropping `stylint-config-standard`. I agree that it doesn't make sense to have it if Prettier takes care of the stylistic rules.

PR on it's way :)

**Comment by schalkneethling** [comment]
@mindy Looking at https://www.npmjs.com/package/stylelint-config-recommended-scss it looks like all it does is what https://www.npmjs.com/package/stylelint-config-recommended already does i.e.

"It turns on all the possible errors rules within stylelint. Use it as is or as a foundation for your own config."

Agree? If so, then we can remove the need for the `stylelint-config-recommended-scss` dependency.

**Comment by mindy** [comment]
Agreed, we can drop the dependency. Thank you for looking at this @schalkneethling

**Comment by mindy** [comment]
I will take a look at stylelint-config-sass-guidelines within the next week!  👀

**Comment by mindy** [comment]
I looked at `stylelint-config-sass-guidelines` and `stylelint-a11y/recommended` and the rules they add seem reasonable and useful. In sass-guidelines there were some rules that eventually get overridden (`max-nesting-depth` and a few that are in the Prettier plugin like `string-quotes`), but I think overall it adds value. 

I opened up https://github.com/schalkneethling/mdn-minimalist/pull/42 to remove rules that are covered by sass-guidelines.
